### PR TITLE
feat: add posenet key-point estimation model

### PR DESCRIPTION
**Pull request by bhavikapanara**
For fall-detection, find the key-points of the human body by running Posenet TF Lite model.

### CODE REVIEW

**Comment by ivelin** [comment]
Thank you, @bhavikapanara. Getting closer to the goal. 

Several comments:

1. Please notice that the CI tests fail. We need all CI checks to pass:
https://travis-ci.com/github/ambianic/ambianic-edge/jobs/399645247#L3795

2. Please take a look at the pep8speaks comments above. See if you can eliminate some of these warnings.

3. There is also a fail message by the commit-lint-pr bot. Please take a closer look at that for your next commit. Thank you.

4. We need the CLA signed. See the comment by the CLAassistant bot above.

Thank you!

Ivelin

**Review by ivelin — CHANGES_REQUESTED** [review]
This is a good start. Next we need this to integrate in the Ambianic pipeline framework. Please see the [current fall detection](https://github.com/ambianic/ambianic-edge/blob/fall-detect/src/ambianic/pipeline/ai/fall_detect.py) class and either extend or refactor it to accommodate your improvements.

**Comment by ivelin** [comment]
@bhavikapanara are you still working on this PR?

**Comment by bhavikapanara** [comment]
> @bhavikapanara are you still working on this PR?
yes...I am still working on this

**Pull request closed without merging**
