### PR TITLE
feat: improve watch timeout

### PR DESCRIPTION
**Pull request by muka**

### CODE REVIEW

**Comment by ivelin** [comment]
Hi @muka , just checking if you want this PR merged or you'd rather replace it with the switch from inotify to watchtower?

**Comment by muka** [comment]
Personally not against inotify as long it does the job. Anyway would make sense to test a library with more adoption.

Can we merge this PR and track the lib switch as feature request?

If build fails once again, we'll prioritize it.

What do you think?

**Comment by ivelin** [comment]
Works for me. Merging now.

**Comment by ivelin** [comment]
Looks like the poll time increase isn't a reliable workaround. The main CI build failed again on the same test:
https://travis-ci.com/github/ambianic/ambianic-edge/jobs/372828550#L3776

**Pull request merged**
