### PR TITLE
fix: separate inference output formatting for each detection model; closes #254

### LINKED ISSUE #254: [BUG] Pose Engine returns pose coordinates as original image pixel coordinates
**Describe the bug**
Currently pose engine returns pose keypoint coordinates as pixel coordinates in the original input image.
This is not ideal, because we send over the wire to the UI timeline just a thumbnail image, which is a scaled down lighter version of the original image.

To be consistent with other detection models, pose engine should return key points as relative values from 0 to 1 and let the visualization component calculate pixel coordinates right before they are shown to the user.

For privacy concerns, we may not even show the original image or thumbnail to some users, but instead only the stick figure with the pose keypoints.

**Additional context**
[See here](https://github.com/ambianic/ambianic-edge/blob/17873da6fc7d61ce0ff3180d0db4bbc0c0837c84/src/ambianic/pipeline/ai/pose_engine.py#L128).

### PR DESCRIPTION
**Pull request by bhavikapanara**

### CODE REVIEW

**Comment by ivelin** [comment]
@bhavikapanara I did a first pass review and I think conceptually you captured the essence of the issue. I will do a second pass tomorrow and look for any details that I might have overlooked today before merging. Thank you!

**Review by ivelin — CHANGES_REQUESTED** [review]
@bhavikapanara notice that the CI fails with testsuite errors. 

Please make sure all CI checks pass. 

Also please take care of the pep8 lint errors. I suggest installing pylama or another local linter in your IDE.

Thank you!

**Comment by ivelin** [comment]
@bhavikapanara did you test these changes against the UI. All looking good in the timeline view?

**Comment by bhavikapanara** [comment]
> @bhavikapanara did you test these changes against the UI. All looking good in the timeline view?

@ivelin I have checked against UI and it is working

**Comment by bhavikapanara** [comment]
> @bhavikapanara notice that the CI fails with testsuite errors.
> 
> Please make sure all CI checks pass.
> 
> Also please take care of the pep8 lint errors. I suggest installing pylama or another local linter in your IDE.
> 
> Thank you!

@ivelin I have tried to fix all pep8 error...but still, there are some lines left. will do it.
And also working to resolve CI fails

**Comment by bhavikapanara** [comment]
@ivelin CI test fails for test_avsource.py file.

Working to solve it.

**Pull request merged**
