### PR TITLE
Logging and conditional testing for configuration processing

### PR DESCRIPTION
**Pull request by dcmartin**
Added and changed log messages to conform to pattern associated with pipeline configuration processing for the purposes of debugging.

I observe no changes in operational functionality of this repository, but did identify a requirement for `source_id` to be added to the `sources:` section in the `config.yaml` file; FWIW, it worked for me.

I am generating the `config.yaml` as part of a Home Assistant addon for ambianic; see http://github.com/dcmartin/hassio-addons and the `ambianic/` directory; building the container requires a clone of the `ambianic-edge` repository to be in the `ambianic-edge/` directory.

I made changes to the return values from True to False in the `pipeline/interpreter.py` (see line 319 for example) when the conditional indicated a failure.

I am still failing to establish complete functionality using the addon (AFAICT), but the PWA is now connecting.

### CODE REVIEW

**Comment by dcmartin** [comment]
I think there is more wrong w/ the processing of the YAML

**Comment by dcmartin** [comment]
draft

**Comment by ivelin** [comment]
@dcmartin this PR is in draft status since July. Do you need to still work on it or its ready for review?

**Comment by ivelin** [comment]
@dcmartin  Closing this draft PR due to inactivity. Let me know if you'd like to complete it.

**Pull request closed without merging**
