### PR TITLE
fix: configuration bug fixes

### LINKED ISSUE #224: [BUG] auto update fails after dynaconf refactor
**Describe the bug**

watchtower updated to the new dynaconf edge version and it now fails due to inability to read a previous config.yaml format. We should push a new version that gracefully converts a previous config.yaml to the new version without bricking edge.

**To Reproduce**
1. Get an existing ambianic edge config.yaml which uses yaml entity references
2. Download and run new docker image with dynaconf patch
3. Look at  docker-compose logs

```
ambianic-edge    | 2020-11-17 22:21:12 INFO /workspace/peerjs/ext/http-proxy.py.peer_open(91): Peer signaling connection open.
ambianic-edge    | 2020-11-17 22:21:12 INFO /workspace/peerjs/ext/http-proxy.py.peer_open(105): savedPeerId: 35bdf700-cbff-4358-8a0e-d1ee70ceef67
ambianic-edge    | Traceback (most recent call last):
ambianic-edge    |   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
ambianic-edge    |     "__main__", mod_spec)
ambianic-edge    |   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
ambianic-edge    |     exec(code, run_globals)
ambianic-edge    |   File "/opt/ambianic-edge/src/ambianic/__main__.py", line 46, in <module>
ambianic-edge    |     main()
ambianic-edge    |   File "/opt/ambianic-edge/src/ambianic/__main__.py", line 19, in main
ambianic-edge    |     ambianic.server_instance.start()
ambianic-edge    |   File "/opt/ambianic-edge/src/ambianic/server.py", line 129, in start
ambianic-edge    |     logger.configure(config.get("logging"))
ambianic-edge    |   File "/usr/local/lib/python3.7/dist-packages/dynaconf/base.py", line 141, in __getattr__
ambianic-edge    |     self._setup()
ambianic-edge    |   File "/usr/local/lib/python3.7/dist-packages/dynaconf/base.py", line 192, in _setup
ambianic-edge    |     settings_module=settings_module, **self._kwargs
ambianic-edge    |   File "/usr/local/lib/python3.7/dist-packages/dynaconf/base.py", line 255, in __init__
ambianic-edge    |     self.execute_loaders()
ambianic-edge    |   File "/usr/local/lib/python3.7/dist-packages/dynaconf/base.py", line 948, in execute_loaders
ambianic-edge    |     self, env=env, silent=silent, key=key, filename=filename
ambianic-edge    |   File "/usr/local/lib/python3.7/dist-packages/dynaconf/loaders/__init__.py", line 125, in settings_loader
ambianic-edge    |     obj, filename=mod_file, env=env, silent=silent, key=key
ambianic-edge    |   File "/usr/local/lib/python3.7/dist-packages/dynaconf/loaders/yaml_loader.py", line 52, in load
ambianic-edge    |     loader.load(filename=filename, key=key, silent=silent)
ambianic-edge    |   File "/usr/local/lib/python3.7/dist-packages/dynaconf/loaders/base.py", line 62, in load
ambianic-edge    |     source_data = self.get_source_data(files)
ambianic-edge    |   File "/usr/local/lib/python3.7/dist-packages/dynaconf/loaders/base.py", line 83, in get_source_data
ambianic-edge    |     content = self.file_reader(open_file)
ambianic-edge    |   File "/usr/local/lib/python3.7/dist-packages/dynaconf/vendor/ruamel/yaml/main.py", line 341, in safe_load
ambianic-edge    |     def safe_load(stream,version=_A):return load(stream,SafeLoader,version)
ambianic-edge    |   File "/usr/local/lib/python3.7/dist-packages/dynaconf/vendor/ruamel/yaml/main.py", line 323, in load
ambianic-edge    |     try:return loader._constructor.get_single_data()
ambianic-edge    |   File "/usr/local/lib/python3.7/dist-packages/dynaconf/vendor/ruamel/yaml/constructor.py", line 107, in get_single_data
ambianic-edge    |     node=self.composer.get_single_node()
ambianic-edge    |   File "/usr/local/lib/python3.7/dist-packages/dynaconf/vendor/ruamel/yaml/composer.py", line 34, in get_single_node
ambianic-edge    |     if not A.parser.check_event(StreamEndEvent):B=A.compose_document()
ambianic-edge    |   File "/usr/local/lib/python3.7/dist-packages/dynaconf/vendor/ruamel/yaml/composer.py", line 37, in compose_document
ambianic-edge    |     def compose_document(A):A.parser.get_event();B=A.compose_node(_A,_A);A.parser.get_event();A.anchors={};return B
ambianic-edge    |   File "/usr/local/lib/python3.7/dist-packages/dynaconf/vendor/ruamel/yaml/composer.py", line 49, in compose_node
ambianic-edge    |     elif A.parser.check_event(MappingStartEvent):E=A.compose_mapping_node(B)
ambianic-edge    |   File "/usr/local/lib/python3.7/dist-packages/dynaconf/vendor/ruamel/yaml/composer.py", line 74, in compose_mapping_node
ambianic-edge    |     while not B.parser.check_event(MappingEndEvent):G=B.compose_node(A,_A);H=B.compose_node(A,G);A.value.append((G,H))
ambianic-edge    |   File "/usr/local/lib/python3.7/dist-packages/dynaconf/vendor/ruamel/yaml/composer.py", line 49, in compose_node
ambianic-edge    |     elif A.parser.check_event(MappingStartEvent):E=A.compose_mapping_node(B)
ambianic-edge    |   File "/usr/local/lib/python3.7/dist-packages/dynaconf/vendor/ruamel/yaml/composer.py", line 74, in compose_mapping_node
ambianic-edge    |     while not B.parser.check_event(MappingEndEvent):G=B.compose_node(A,_A);H=B.compose_node(A,G);A.value.append((G,H))
ambianic-edge    |   File "/usr/local/lib/python3.7/dist-packages/dynaconf/vendor/ruamel/yaml/composer.py", line 49, in compose_node
ambianic-edge    |     elif A.parser.check_event(MappingStartEvent):E=A.compose_mapping_node(B)
ambianic-edge    |   File "/usr/local/lib/python3.7/dist-packages/dynaconf/vendor/ruamel/yaml/composer.py", line 74, in compose_mapping_node
ambianic-edge    |     while not B.parser.check_event(MappingEndEvent):G=B.compose_node(A,_A);H=B.compose_node(A,G);A.value.append((G,H))
ambianic-edge    |   File "/usr/local/lib/python3.7/dist-packages/dynaconf/vendor/ruamel/yaml/composer.py", line 41, in compose_node
ambianic-edge    |     if D not in A.anchors:raise ComposerError(_A,_A,'found undefined alias %r'%utf8(D),C.start_mark)
ambianic-edge    | dynaconf.vendor.ruamel.yaml.composer.ComposerError: found undefined alias 'secret_uri_front_door_camera'
ambianic-edge    |   in "/workspace/config.yaml", line 22, column 10
ambianic-edge exited with code 1
ambianic-edge    | Reading package lists...
```

**Expected behavior**

Clean upgrade that's transparent to the user. Read config.yaml with a standard yaml library and convert it to a simplified format that dynaconf understands. Then save the new version back to config.yaml. Log an INFO message letting the user know about the conversion with a link to online document that explains the new format.

**Host environment (please complete the following information):**
 - Hardware: Raspberry Pi
 - OS: Raspbian OS Buster
 - Container docker, docker-compose, watchtower
 - Version: Ambianic-edge v1.8.5 
https://github.com/ambianic/ambianic-edge/releases/tag/v1.8.5

**Additional context**

Related to #222

### LINKED ISSUE #248: [BUG] Dynamic config update error
**Describe the bug**
config.yaml update while the ambianic-edge docker image is running results in error

```
ambianic-edge    | 2020-12-12 06:30:13 INFO /opt/ambianic-edge/src/ambianic/pipeline/ai/image_detection.py._log_stats(162): Inference time 334.03 ms, 2.08 fps in pipeline area_watch
ambianic-edge    | Exception in thread Thread-1:
ambianic-edge    | Traceback (most recent call last):
ambianic-edge    |   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
ambianic-edge    |     self.run()
ambianic-edge    |   File "/usr/local/lib/python3.7/dist-packages/watchdog/observers/api.py", line 199, in run
ambianic-edge    |     self.dispatch_events(self.event_queue, self.timeout)
ambianic-edge    |   File "/usr/local/lib/python3.7/dist-packages/watchdog/observers/api.py", line 372, in dispatch_events
ambianic-edge    |     handler.dispatch(event)
ambianic-edge    | AttributeError: 'function' object has no attribute 'dispatch'
ambianic-edge    | 
ambianic-edge    | 2020-12-12 06:30:14 INFO /opt/ambianic-edge/src/ambianic/pipeline/ai/image_detection.py._log_stats(162): Inference time 334.53 ms, 2.11 fps in pipeline area_watch
```

**To Reproduce**
1. Pull latest image
2. Run ambianic-edge
3. Change config.yaml
4. See error in log

**Expected behavior**
New config should be loaded without errors.

**Host environment (please complete the following information):**
 - Hardware: Raspberry Pi 4
 - OS: Ambianic OS
 - Container docker
 - Version 1.12

### PR DESCRIPTION
**Pull request by muka**
- Fixed reload, now the server correctly reload if a config file is changed. Fix #248. 
- Added secrets implementation. Fix #224

### CODE REVIEW

**Comment by ivelin** [comment]
Cool. Will review as soon as I'm done with the fall detection release.

**Comment by ivelin** [comment]
@muka the [PR fails the arm architecture tests](https://github.com/ambianic/ambianic-edge/pull/251/checks?check_run_id=1543113352#step:3:3878):

```
=================================== FAILURES ===================================
______________________________ test_config_change ______________________________

    def test_config_change():
        _dir = os.path.dirname(os.path.abspath(__file__))
        config_file = os.path.join(_dir, 'test-config-no-pipelines.yaml')
        load_config(config_file, True)
        hb_flag = threading.Event()
        srv, t = _start_mock_server(work_dir=_dir, heartbeat_flag=hb_flag)
        hb_flag.wait(timeout=3)
        Path(config_file).touch()
        time.sleep(1)
        assert hb_flag.is_set()
        assert srv.config_changed
>       _stop_mock_server(server=srv, thread=t)

tests/test_startup.py:159: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

server = <test_startup.MockAmbianicServer object at 0xfc6de7f0>
thread = <Thread(Thread-32, started daemon 4233000032)>

    def _stop_mock_server(server=None, thread=None):
        assert server
        assert thread
        server.stop()
        thread.join(timeout=10)
>       assert not thread.is_alive()
E       assert not True
E        +  where True = <bound method Thread.is_alive of <Thread(Thread-32, started daemon 4233000032)>>()
E        +    where <bound method Thread.is_alive of <Thread(Thread-32, started daemon 4233000032)>> = <Thread(Thread-32, started daemon 4233000032)>.is_alive

tests/test_startup.py:60: AssertionError
```


Is it possible that the file change detection does not work when its initiated outside of docker to a file on a mapped docker volume? Maybe the OS signal does not travel from the hosting OS through docker to the monitoring library?

**Comment by ivelin** [comment]
related to https://github.com/ambianic/ambianic-edge/issues/256#issuecomment-743972487

**Comment by muka** [comment]
This happens on my PC too randomly while running tests.  Will review the PR thanks

**Comment by muka** [comment]
Test seems to work on my test env now. Waiting for the CI to complete.

Follows a log of a successfully reloaded configuration on the py (tested  in debug mode) where the pipeline source has been switched 

```
2020-12-14 06:49:59 INFO /workspace/src/ambianic/pipeline/avsource/gst_process.py._on_new_sample(176): GstService adding sample to out_queue.
2020-12-14 06:49:59 INFO /workspace/src/ambianic/server.py.dispatch(124): Configuration file changed, stopping Ambianic server
2020-12-14 06:49:59 INFO /workspace/src/ambianic/server.py.stop(177): Stopping server...
2020-12-14 06:50:00 INFO /workspace/src/ambianic/pipeline/ai/image_detection.py._log_stats(162): Inference time 380.12 ms, 0.45 fps in pipeline area_watch
2020-12-14 06:50:00 INFO /workspace/src/ambianic/server.py.start(162): Service exit requested.
2020-12-14 06:50:00 INFO /workspace/src/ambianic/pipeline/interpreter.py.stop(90): Pipeline server job stopping...
2020-12-14 06:50:00 INFO /workspace/src/ambianic/pipeline/interpreter.py.stop(221): pipeline jobs stopping...
2020-12-14 06:50:00 INFO /workspace/src/ambianic/pipeline/interpreter.py.stop(523): Requesting pipeline elements to stop... Pipeline
2020-12-14 06:50:00 INFO /workspace/src/ambianic/pipeline/avsource/av_element.py.stop(335): Entering stop method ... AVSourceElement
2020-12-14 06:50:00 INFO /workspace/src/ambianic/pipeline/avsource/av_element.py.stop(338): Exiting stop method. AVSourceElement
2020-12-14 06:50:00 INFO /workspace/src/ambianic/pipeline/interpreter.py.stop(527): Completed request to pipeline elements to stop. Pipeline
2020-12-14 06:50:01 ERROR /workspace/src/ambianic/pipeline/store.py.process_sample(165): Error AttributeError("'NoneType' object has no attribute 'save'") while saving sample {'image': <PIL.Image.Image image mode=RGB size=2592x1944 at 0xA9A53B90>, 'inference_result': None, 'inference_meta': {'display': 'Fall Detection'}}
Traceback (most recent call last):
  File "/workspace/src/ambianic/pipeline/store.py", line 161, in process_sample
    inference_meta=inference_meta)
  File "/workspace/src/ambianic/pipeline/store.py", line 114, in _save_sample
    thumbnail.save(thumbnail_path)
AttributeError: 'NoneType' object has no attribute 'save'
2020-12-14 06:50:01 INFO /workspace/src/ambianic/pipeline/avsource/gst_process.py._stop_handler(367): GST service received stop signal
2020-12-14 06:50:02 INFO /workspace/src/ambianic/pipeline/avsource/gst_process.py.run(398): Stopped GstService
2020-12-14 06:50:02 INFO /workspace/src/ambianic/pipeline/avsource/gst_process.py.start_gst_service(413): Exiting GST process
2020-12-14 06:50:03 INFO /workspace/src/ambianic/pipeline/avsource/av_element.py.start(301): Stopped AVSourceElement
2020-12-14 06:50:03 INFO /workspace/src/ambianic/pipeline/interpreter.py.start(470): Started Pipeline
2020-12-14 06:50:03 INFO /workspace/src/ambianic/util.py.run(87): Thread #2807325792 for job Pipeline stopped
2020-12-14 06:50:03 INFO /workspace/src/ambianic/pipeline/interpreter.py.stop(228): pipeline jobs stopped.
2020-12-14 06:50:03 INFO /workspace/src/ambianic/pipeline/interpreter.py.stop(97): Pipeline server job stopped.
2020-12-14 06:50:03 INFO /workspace/src/ambianic/webapp/flaskr.py.stop(107): Flask server job stopping...
2020-12-14 06:50:03 INFO /workspace/src/ambianic/util.py.run(87): Thread #2929718368 for job FlaskJob stopped
2020-12-14 06:50:03 INFO /workspace/src/ambianic/webapp/flaskr.py.stop(110): Flask server job stopped.
2020-12-14 06:50:03 WARNING /workspace/src/ambianic/server.py.start_watch_config(70): File /workspace/secrets.yaml not found, it will not be watched for changes.
Log messages directed to ./data/ambianic-log.txt
2020-12-14 06:50:03 INFO /workspace/src/ambianic/logger.py.configure(82): Logging configured with level INFO
2020-12-14 06:50:03 INFO /workspace/src/ambianic/server.py.start(141): Starting Ambianic server...
2020-12-14 06:50:03 INFO /workspace/src/ambianic/pipeline/interpreter.py.start(72): PipelineServer server job starting...
2020-12-14 06:50:03 INFO /workspace/src/ambianic/pipeline/interpreter.py.get_pipelines(45): loading area_watch pipeline configuration
2020-12-14 06:50:03 INFO /workspace/src/ambianic/pipeline/interpreter.py.load_elements(310): Pipeline area_watch loading next element: {'source': 'picamera'}
2020-12-14 06:50:03 INFO /workspace/src/ambianic/pipeline/interpreter.py.load_elements(339): Pipeline area_watch adding element name source with class <class 'ambianic.pipeline.avsource.av_element.AVSourceElement'> and config {'uri': 'picamera', 'type': 'video', 'live': True, 'source_id': 'picamera'}
2020-12-14 06:50:03 INFO /workspace/src/ambianic/pipeline/interpreter.py.load_elements(310): Pipeline area_watch loading next element: {'detect_objects': {'ai_model': 'image_detection', 'confidence_threshold': 0.6}}
2020-12-14 06:50:03 INFO /workspace/src/ambianic/pipeline/interpreter.py.load_elements(339): Pipeline area_watch adding element name detect_objects with class <class 'ambianic.pipeline.ai.object_detect.ObjectDetector'> and config {'ai_model': 'image_detection', 'confidence_threshold': 0.6, 'model': {'tflite': 'ai_models/mobilenet_ssd_v2_coco_quant_postprocess.tflite', 'edgetpu': 'ai_models/mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite'}, 'labels': 'ai_models/coco_labels.txt', 'ai_model_id': 'image_detection'}
```

**Pull request merged**
