### PR TITLE
fix: sources API

### PR DESCRIPTION
**Pull request by muka**
This PR fixes the sources HTTP API reload capabilities. Functionally it is a step back as now all the pipelines will be restarted without fine grained checks.

Anyway we can recover such level of functionalities later on if required.

### CODE REVIEW

**Comment by ivelin** [comment]
@muka Have you noticed that codecov is failing? Would you be able to add a few more tests to keep the coverage at a good level.

**Comment by muka** [comment]
I noticed but considered just the overall, will check this

**Comment by muka** [comment]
I think the PR is good for review. That codecov patch check is too picky for me!

**Comment by ivelin** [comment]
Awesome. Merging. Thank you!

**Pull request merged**
